version: "3.7"
services:
  ref_near_web:
    container_name: ref_near_web
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
      - web
    expose:
      - 80
    env_file:
      - .env.production

networks:
  web:
    external: true
  internal:
    external: true
