log:
  level: ERROR

entryPoints:
  web:
    address: :80

  web-secure:
    address: :443

  # postgres:
  #   address: :5432

certificatesResolvers:
  myhttpchallenge:
    acme:
      email: miroslav.smeral@gmail.cz
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
api: {}

providers:
  # docker:
  #   endpoint: unix:///var/run/docker.sock
  #   exposedByDefault: false
  #   watch: true
  file:
    filename: /config.yml
    watch: true
